# -*- coding: utf-8 -*-
"""AI_glossary_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8qDexSomtPWfts9RMhBDxkohnEkmHkh

### **Exploratory Data Analysis (EDA)**
"""

import json
import pandas as pd
import re
from collections import Counter

# ============================================================
# 1. Load dataset
# ============================================================
with open("ai_glossary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)
print("=" * 50)
print("📦 Raw dataset structure")
print("=" * 50)
print(f"  Total terms       : {len(df)}")
print(f"  Available columns : {list(df.columns)}")

# ============================================================
# 2. Check missing values
# ============================================================
print("\n" + "=" * 50)
print("🔍 Missing Values (Null Values)")
print("=" * 50)
print(df.isnull().sum().to_string())

# ============================================================
# 3. Check duplicates
# ============================================================
print("\n" + "=" * 50)
print("♻️  Duplicates")
print("=" * 50)
dup_terms = df[df.duplicated(subset="term", keep=False)]
print(f"  Duplicate terms (term)        : {df.duplicated(subset='term').sum()}")

dup_defs = df[df.duplicated(subset="definition", keep=False)]
print(f"  Duplicate definitions         : {df.duplicated(subset='definition').sum()}")

if not dup_defs.empty:
    print("\n  Example duplicate definitions:")
    print(dup_defs[["term", "definition"]].head(6).to_string(index=False))

# ============================================================
# 4. Check redirect entries
# ============================================================
print("\n" + "=" * 50)
print("🔀 Redirect Entries (redirect_to)")
print("=" * 50)
if "redirect_to" in df.columns:
    redirects = df[df["redirect_to"].notna()]
    print(f"  Number of redirected terms : {len(redirects)}")
    print("\n  Examples:")
    print(redirects[["term", "redirect_to"]].head(5).to_string(index=False))

# ============================================================
# 5. Check unusual characters (Arabic diacritics / hidden chars)
# ============================================================
print("\n" + "=" * 50)
print("⚠️  Unusual characters in definitions")
print("=" * 50)

# Arabic diacritics range and Arabic Unicode block
arabic_pattern = re.compile(r'[\u0600-\u06FF\u064B-\u065F]')
dirty = df[df["definition"].apply(lambda x: bool(arabic_pattern.search(str(x))))]
print(f"  Definitions with hidden Arabic characters : {len(dirty)}")
if not dirty.empty:
    print("\n  Examples:")
    for _, row in dirty.head(5).iterrows():
        flagged = [f"U+{ord(c):04X}" for c in row["definition"] if arabic_pattern.search(c)]
        print(f"  [{row['term']}]  →  Characters: {flagged}")

# ============================================================
# 6. Check "Also called" pattern
# ============================================================
print("\n" + "=" * 50)
print("📎 Definitions containing 'Also called'")
print("=" * 50)
also_called = df[df["definition"].str.contains("Also called", case=False, na=False)]
print(f"  Count : {len(also_called)}")
print("\n  Examples:")
print(also_called[["term", "definition"]].head(4).to_string(index=False))

# ============================================================
# 7. Definition length statistics
# ============================================================
print("\n" + "=" * 50)
print("📏 Definition length statistics (in words)")
print("=" * 50)
df["def_length"] = df["definition"].apply(lambda x: len(str(x).split()))
print(df["def_length"].describe().round(1).to_string())
short = df[df["def_length"] < 5]
print(f"\n  Very short definitions (< 5 words) : {len(short)}")
if not short.empty:
    print(short[["term", "definition"]].to_string(index=False))

print("\n✅ Analysis completed — ready for Step 2 (Cleaning)")

"""### **Data Cleaning**"""

import json
import pandas as pd
import re

# ============================================================
# 1. Load dataset
# ============================================================
with open("/content/ai_glossary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

df = pd.DataFrame(data)
print(f"✅ Loaded — total terms before cleaning: {len(df)}")

# ============================================================
# 2. Remove hidden Arabic characters (U+0650 etc.)
# ============================================================
def remove_arabic_chars(text):
    if pd.isna(text):
        return text
    return re.sub(r'[\u0600-\u06FF\u064B-\u065F]', '', text).strip()

df["definition"] = df["definition"].apply(remove_arabic_chars)
df["term"]       = df["term"].apply(remove_arabic_chars)

print(f"\n🧹 Done: removed hidden Arabic characters")

# ============================================================
# 3. Clean "Also called" phrases from definitions
#    Goal: keep only the main definition
#    Example:
#      Before: "A CV task. Also called 'HAR'."
#      After:  "A CV task."
# ============================================================
def clean_also_called(text):
    if pd.isna(text):
        return text
    cleaned = re.sub(r'\s*Also called[^.]*\.?', '', text, flags=re.IGNORECASE).strip()
    if cleaned and not cleaned.endswith('.'):
        cleaned += '.'
    return cleaned

df["definition"] = df["definition"].apply(clean_also_called)
print(f"🧹 Done: cleaned 'Also called' phrases")

# ============================================================
# 4. Handle Redirect Entries
#    We have 127 redirect terms pointing to others
#    Decision: remove them because they are duplicates
#    (LLM will generate explanation from original term)
# ============================================================
before = len(df)
df_clean = df[df["redirect_to"].isna()].copy()
removed  = before - len(df_clean)
print(f"🧹 Done: removed {removed} redirect entries — remaining {len(df_clean)} terms")

# ============================================================
# 5. Remove "See X" empty definitions
# ============================================================
see_pattern = df_clean["definition"].str.match(r'^See\s+"?.+', case=False, na=False)
df_clean = df_clean[~see_pattern].copy()
print(f"🧹 Done: removed 'See X' empty definitions")

# ============================================================
# 6. Trim whitespace
# ============================================================
df_clean["term"]       = df_clean["term"].str.strip()
df_clean["definition"] = df_clean["definition"].str.strip()

# ============================================================
# 7. Keep only relevant columns
# ============================================================
df_clean = df_clean[["term", "definition"]].reset_index(drop=True)

# ============================================================
# 8. Final check
# ============================================================
print("\n" + "=" * 50)
print("📊 Cleaning Results")
print("=" * 50)
print(f"  Before cleaning : 1242 terms")
print(f"  After cleaning  : {len(df_clean)} terms")
print(f"  Removed         : {1242 - len(df_clean)} terms")

print("\n🔍 Quality check:")

arabic_remaining = df_clean["definition"].apply(
    lambda x: bool(re.search(r'[\u0600-\u06FF]', str(x)))
).sum()

also_remaining = df_clean["definition"].str.contains("Also called", case=False, na=False).sum()
dup_remaining  = df_clean.duplicated(subset="definition").sum()

print(f"  Remaining Arabic characters : {arabic_remaining}  {'✅' if arabic_remaining == 0 else '⚠️'}")
print(f"  Remaining 'Also called'     : {also_remaining}   {'✅' if also_remaining == 0 else '⚠️'}")
print(f"  Remaining duplicates        : {dup_remaining}   {'✅' if dup_remaining == 0 else '⚠️'}")

print("\n📋 Sample cleaned data:")
print(df_clean.head(5).to_string(index=False))

# ============================================================
# 9. Save cleaned dataset
# ============================================================
output_path = "/content/ai_glossary.json"
df_clean.to_json(output_path, orient="records", force_ascii=False, indent=2)

print(f"\n💾 Saved: ai_glossary.json")
print("✅ Cleaning completed — ready for Step 3 (Prompt Engineering)")

# Download the cleaned dataset file to your local machine
from google.colab import files
files.download(output_path)

"""Open AI"""

import json

with open("/content/ai_glossary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

from openai import OpenAI

client = OpenAI(api_key="OPENAI_API_KEY")

results = []

for item in data[:20]:
    term = item["term"]
    definition = item["definition"]

    prompt = f"""
You are an AI educational tutor.

Term: {term}
Definition: {definition}

Task:
1. Rewrite the definition in a simple way
2. Give a real-world example
3. Give an analogy

Return the answer in clear sections.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    results.append({
        "term": term,
        "original_definition": definition,
        "ai_output": response.choices[0].message.content
    })

print("Done")

"""### **Testing the code**"""

import json

# ===============================
# Load data + output container
# ===============================
results = []

batch_size = 100  # 🔥 you can change it (50 / 100 / 200)

# ===============================
# Loop in batches (safe + scalable)
# ===============================
for start in range(0, len(data), batch_size):
    batch = data[start:start + batch_size]

    print(f"🚀 Processing batch {start} to {start + len(batch)}")

    for item in batch:
        term = item["term"]
        definition = item["definition"]

        # ===============================
        # Prompt engineering
        # ===============================
        prompt = f"""
You are an AI educational tutor.

Term: {term}
Definition: {definition}

Task:
1. Rewrite the definition in a simple way
2. Give a real-world example
3. Give an analogy

IMPORTANT:
Return ONLY a valid JSON object (no extra text):

{{
  "simple_definition": "...",
  "example": "...",
  "analogy": "..."
}}
"""

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": prompt}]
        )

        ai_text = response.choices[0].message.content

        try:
            parsed = json.loads(ai_text)

            results.append({
                "term": term,
                "original_definition": definition,
                "simple_definition": parsed.get("simple_definition", ""),
                "example": parsed.get("example", ""),
                "analogy": parsed.get("analogy", "")
            })

        except json.JSONDecodeError:
            print(f"⚠️ JSON error skipped: {term}")
            continue

    # ===============================
    # AUTO SAVE after each batch
    # ===============================
    with open("ai_glossary_enhanced.json", "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"💾 Saved progress: {len(results)} items")

print("🎉 Done processing all data!")

import json

results = []

for item in data[:10]:  # Try first on a small sample
    term = item["term"]
    definition = item["definition"]

    prompt = f"""
You are an AI educational tutor.

Term: {term}
Definition: {definition}

Task:
1. Rewrite the definition in a simple way
2. Give a real-world example
3. Give an analogy

IMPORTANT:
Return ONLY a valid JSON object (no extra text) in this format:

{{
  "simple_definition": "...",
  "example": "...",
  "analogy": "..."
}}
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    ai_text = response.choices[0].message.content

    try:
        parsed = json.loads(ai_text)

        results.append({
            "term": term,
            "original_definition": definition,
            "simple_definition": parsed.get("simple_definition", ""),
            "example": parsed.get("example", ""),
            "analogy": parsed.get("analogy", "")
        })

    except json.JSONDecodeError:
        print(f"⚠️ Skipped term بسبب JSON error: {term}")
        continue

print("Done processing sample data")

import json

with open("ai_glossary_enhanced.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print("Saved successfully")