# -*- coding: utf-8 -*-
"""fastapi_backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjTpsVQCU7LFOZZa33mYrvg6_Wm5KDng
"""

from fastapi import FastAPI, HTTPException
import json

app = FastAPI()

with open("ai_glossary_enhanced.json", "r", encoding="utf-8") as f:
    data = json.load(f)

@app.get("/")
def home():
    return {"message": "API is running"}

@app.get("/term/{term_name}")
def get_term(term_name: str):
    for item in data:
        if item["term"].lower() == term_name.lower():
            return item
    raise HTTPException(status_code=404, detail="Not found")

!uvicorn main:app --host 0.0.0.0 --port 8000